export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const TOOGLE_SIDEBAR = 'TOOGLE_SIDEBAR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_PIG_BEGIN = 'CREATE_PIG_BEGIN'
export const CREATE_PIG_SUCCESS = 'CREATE_PIG_SUCCESS'
export const CREATE_PIG_ERROR = 'CREATE_PIG_ERROR'

export const GET_PIGS_BEGIN = 'GET_PIGS_BEGIN'
export const GET_PIGS_SUCCESS = 'GET_PIGS_SUCCESS'

export const SET_EDIT_PIG = 'SET_EDIT_PIG'

export const DELETE_PIG_BEGIN = 'DELETE_PIG_BEGIN'
export const DELETE_PIG_ERROR = 'DELETE_PIG_ERROR'

export const EDIT_PIG_BEGIN = 'EDIT_PIG_BEGIN'
export const EDIT_PIG_SUCCESS = 'EDIT_PIG_SUCCESS'
export const EDIT_PIG_ERROR = 'EDIT_PIG_ERROR'